import Image from "next/image";
import Link from "next/link";
import StoreHeader from "@/components/store/StoreHeader";
import CollectionCard from "@/components/store/CollectionCard";
import { collections } from "@/components/store/catalog";

export default function Home() {
  return <main className="bg-[#fbfaf8] text-[#1d1c1a]"><StoreHeader />
    <section className="mx-auto grid max-w-7xl gap-9 px-5 py-8 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-12">
      <div className="order-2 max-w-xl lg:order-1"><p className="text-xs font-semibold tracking-[.2em] text-stone-500">THE CONFIDENCE EDIT</p><h1 className="mt-5 text-5xl font-medium leading-[.94] tracking-[-.065em] sm:text-7xl">LOOK YOUR BEST<br />BEFORE YOU BUY</h1><p className="mt-7 max-w-md text-lg leading-8 text-stone-600">Shopping online should feel personal. Discover outfits that truly suit you before making a purchase.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/shop" className="rounded-full bg-[#1d1c1a] px-6 py-3.5 text-sm font-medium text-white transition hover:bg-stone-700">Explore Collection</Link><Link href="/upload" className="rounded-full border border-stone-300 px-6 py-3.5 text-sm font-medium transition hover:border-stone-900">Meet AI Stylist</Link></div></div>
      <div className="relative order-1 h-[30rem] overflow-hidden bg-stone-200 sm:h-[38rem] lg:order-2"><Image src="/images/fashion-retail-hero.png" alt="Editorial fashion portrait in a tailored neutral outfit" fill priority unoptimized sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover object-[62%_top]" /></div>
    </section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.2em] text-stone-500">SHOP THE EDIT</p><h2 className="mt-3 text-4xl font-medium tracking-[-.045em]">Collections with a point of view.</h2></div><Link href="/shop" className="hidden text-sm font-medium underline underline-offset-4 sm:block">View all pieces</Link></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{collections.map((item, index) => <CollectionCard key={item} title={item} index={index} />)}</div></section>
    <section className="border-y border-stone-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold tracking-[.2em] text-violet-700">MEET YOUR AI STYLIST</p><h2 className="mt-4 text-4xl font-medium leading-tight tracking-[-.045em]">The right outfit should feel like a yes before it reaches your door.</h2><p className="mt-5 leading-7 text-stone-600">Upload a clear photo of yourself, tell us where you&apos;re headed, and receive a personal edit that explains exactly why it works for you.</p><Link href="/upload" className="mt-7 inline-block text-sm font-medium underline underline-offset-4">Meet the AI Stylist →</Link></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-violet-50 p-5"><span className="text-2xl">01</span><p className="mt-12 text-lg font-medium">See yourself in the choice.</p></div><div className="rounded-2xl bg-stone-100 p-5"><span className="text-2xl">02</span><p className="mt-12 text-lg font-medium">Understand why it suits you.</p></div><div className="rounded-2xl bg-amber-50 p-5"><span className="text-2xl">03</span><p className="mt-12 text-lg font-medium">Shop with real confidence.</p></div></div></div></section>
    <footer className="border-t border-stone-200 px-5 py-10 text-center text-sm text-stone-500">Fashion Retail · Made for more confident choices.</footer>
  </main>;
}
