export type Product = {
  id: string;
  name: string;
  category: "New Arrivals" | "Men" | "Women" | "Accessories";
  price: number;
  rating: number;
  color: string;
  material: string;
  occasion: string;
  description: string;
  palette: string;
  garment: string;
};

export const products: Product[] = [
  {"id":"linen-overshirt","name":"Linen Overshirt","category":"New Arrivals","price":68,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original linen overshirt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"soft-tailored-blazer","name":"Soft Tailored Blazer","category":"New Arrivals","price":99,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original soft tailored blazer designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"sculpted-knit","name":"Sculpted Knit Top","category":"New Arrivals","price":130,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original sculpted knit top designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"relaxed-trouser","name":"Relaxed Pleat Trouser","category":"New Arrivals","price":161,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original relaxed pleat trouser designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"cotton-utility","name":"Cotton Utility Jacket","category":"New Arrivals","price":192,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original cotton utility jacket designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"fine-rib-polo","name":"Fine Rib Polo","category":"New Arrivals","price":223,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original fine rib polo designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"draped-shirt","name":"Draped Poplin Shirt","category":"New Arrivals","price":254,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original draped poplin shirt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"everyday-coat","name":"Everyday Wool Coat","category":"New Arrivals","price":285,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original everyday wool coat designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"studio-dress","name":"Studio Midi Dress","category":"New Arrivals","price":316,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original studio midi dress designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"weekend-cargo","name":"Weekend Cargo Trouser","category":"New Arrivals","price":347,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original weekend cargo trouser designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-navy-blazer","name":"Navy Sculpted Blazer","category":"Men","price":68,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original navy sculpted blazer designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-merino-crew","name":"Fine Merino Crew","category":"Men","price":99,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original fine merino crew designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-field-jacket","name":"Modern Field Jacket","category":"Men","price":130,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original modern field jacket designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-overshirt","name":"Textured Cotton Overshirt","category":"Men","price":161,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original textured cotton overshirt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-linen-shirt","name":"Relaxed Linen Shirt","category":"Men","price":192,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original relaxed linen shirt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-travel-trouser","name":"Technical Travel Trouser","category":"Men","price":223,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original technical travel trouser designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-topcoat","name":"Wool Topcoat","category":"Men","price":254,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original wool topcoat designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-polo","name":"Fine Gauge Polo","category":"Men","price":285,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original fine gauge polo designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-summer-suit","name":"Summer Weight Suit","category":"Men","price":316,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original summer weight suit designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"men-knit-jacket","name":"Merino Knit Jacket","category":"Men","price":347,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original merino knit jacket designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-column-dress","name":"Silk Column Dress","category":"Women","price":68,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original silk column dress designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-wide-leg","name":"Wide Leg Trouser","category":"Women","price":99,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original wide leg trouser designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-pleated-midi","name":"Pleated Midi Skirt","category":"Women","price":130,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original pleated midi skirt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-soft-jacket","name":"Soft Shoulder Jacket","category":"Women","price":161,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original soft shoulder jacket designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-rib-dress","name":"Rib Knit Dress","category":"Women","price":192,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original rib knit dress designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-wrap-coat","name":"Cashmere Wrap Coat","category":"Women","price":223,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original cashmere wrap coat designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-satin-cami","name":"Satin Bias Cami","category":"Women","price":254,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original satin bias cami designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-cardigan","name":"Cropped Wool Cardigan","category":"Women","price":285,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original cropped wool cardigan designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-asymmetric","name":"Asymmetric Jersey Top","category":"Women","price":316,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original asymmetric jersey top designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"women-shirt-dress","name":"Silk Shirt Dress","category":"Women","price":347,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original silk shirt dress designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-tote","name":"Structured Leather Tote","category":"Accessories","price":68,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original structured leather tote designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-watch","name":"Minimal Steel Watch","category":"Accessories","price":99,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original minimal steel watch designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-scarf","name":"Graphic Silk Scarf","category":"Accessories","price":130,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original graphic silk scarf designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-loafer","name":"Soft Leather Loafer","category":"Accessories","price":161,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original soft leather loafer designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-belt","name":"Brown Leather Belt","category":"Accessories","price":192,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original brown leather belt designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-sneaker","name":"Clean Court Sneaker","category":"Accessories","price":223,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original clean court sneaker designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-sunglasses","name":"Sculpted Sunglasses","category":"Accessories","price":254,"rating":4.8,"color":"Studio","material":"Original studio fabric","occasion":"Weekend","description":"An original sculpted sunglasses designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-crossbody","name":"Compact Crossbody","category":"Accessories","price":285,"rating":4.9,"color":"Studio","material":"Original studio fabric","occasion":"Travel","description":"An original compact crossbody designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-cap","name":"Minimal Cotton Cap","category":"Accessories","price":316,"rating":4.6,"color":"Studio","material":"Original studio fabric","occasion":"Everyday","description":"An original minimal cotton cap designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
  {"id":"acc-jewelry","name":"Fine Chain Necklace","category":"Accessories","price":347,"rating":4.7,"color":"Studio","material":"Original studio fabric","occasion":"Workday","description":"An original fine chain necklace designed for a considered modern wardrobe.","palette":"from-stone-100 via-slate-100 to-stone-200","garment":"bg-stone-600"},
];

export const collections = ["New Arrivals", "Men", "Women", "Accessories"];
